export enum EImageStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum EImageTarget {
  NOTICE_CONTENT = 'NOTICE_CONTENT',
  BANNER = 'BANNER',
  LECTURE_TEXTBOOK = 'LECTURE_TEXTBOOK',
  LECTURE_THUMBNAIL = 'LECTURE_THUMBNAIL',
}
