FROM node:18.14.2-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
EXPOSE 4000
CMD ["npm", "run", "start:production:event-server"]
